# Generated by Django 4.0.4 on 2022-11-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['id', 'slug'], name='Store_resta_id_683119_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['-created'], name='Store_resta_created_748b2b_idx'),
        ),
    ]
