# Generated by Django 4.0.4 on 2022-11-13 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_restaurant_store_resta_id_683119_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['name']},
        ),
    ]
