# Generated by Django 4.0.4 on 2022-11-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_alter_restaurant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['name'], 'verbose_name': 'restaurant', 'verbose_name_plural': 'restaurants'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='Store_produ_id_ab32c8_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug', 'id'], name='Store_produ_slug_385f37_idx'),
        ),
    ]
