# Generated by Django 4.0.4 on 2022-10-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_rename_category_product_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.ManyToManyField(to='Store.category'),
        ),
    ]
