# Generated by Django 4.0.4 on 2022-11-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_remove_restaurant_store_resta_id_683119_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='restaurant',
            name='Store_resta_slug_6188be_idx',
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['id', 'slug'], name='Store_resta_id_683119_idx'),
        ),
    ]
