# Generated by Django 4.0.4 on 2022-06-13 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=1)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(default='123', max_length=100)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('nickname', models.CharField(max_length=50)),
                ('email', models.EmailField(default='123@123.com', max_length=254, unique=True)),
                ('address', models.CharField(default='123', max_length=100)),
                ('phoneNo', models.CharField(default='123', max_length=10)),
                ('birthdate', models.DateTimeField(default=datetime.datetime.now, max_length=10)),
                ('status', models.IntegerField(default=1)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='CustomSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='session key')),
                ('session_data', models.TextField(verbose_name='session data')),
                ('expire_date', models.DateTimeField(db_index=True, verbose_name='expire date')),
                ('account_id', models.IntegerField(db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.CharField(max_length=100)),
                ('secureNo', models.CharField(max_length=5)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
      
    ]
