# Generated by Django 4.0.4 on 2022-05-18 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(default='123', max_length=100)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('email', models.EmailField(default='123@123.com', max_length=254, unique=True)),
                ('address', models.CharField(default='123', max_length=100)),
                ('phoneNo', models.CharField(default='123', max_length=10)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'customer_up',
            },
        ),
    ]
