# Generated by Django 4.0.4 on 2022-05-23 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='birthdate',
            field=models.DateTimeField(default=datetime.datetime.now, max_length=10),
        ),
    ]
