# Generated by Django 4.0.4 on 2022-06-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='null', max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phoneNo',
            field=models.CharField(default='', max_length=10),
        ),
    ]
