# Generated by Django 4.0.4 on 2022-06-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='updateid',
            field=models.IntegerField(default=1),
        ),
    ]
