# Generated by Django 4.0.4 on 2022-06-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_alter_customer_address_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomSession',
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthdate',
            field=models.CharField(max_length=50),
        ),
    ]
