# Generated by Django 4.0.4 on 2022-06-30 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_alter_customer_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
