# Generated by Django 4.0.4 on 2022-06-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_alter_customer_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='update_at',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
