# Generated by Django 4.0.4 on 2022-06-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_alter_customer_birthdate_alter_customer_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phoneNo',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
