# Generated by Django 4.0.4 on 2022-09-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0013_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='update',
        ),
    ]
